CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, name TEXT NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'learner' CHECK(role IN ('learner','instructor','admin')), disabled INTEGER NOT NULL DEFAULT 0, profile TEXT NOT NULL DEFAULT '{}', settings TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS sessions_user ON sessions(user_id);
CREATE TABLE IF NOT EXISTS rate_limits (key TEXT PRIMARY KEY, attempts INTEGER NOT NULL, expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS courses (id TEXT PRIMARY KEY, owner_id TEXT REFERENCES users(id), publication TEXT NOT NULL CHECK(publication IN ('draft','published','archived')), metadata TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS courses_owner ON courses(owner_id, publication);
CREATE TABLE IF NOT EXISTS lessons (id TEXT PRIMARY KEY, course_id TEXT NOT NULL REFERENCES courses(id) ON DELETE CASCADE, module_title TEXT NOT NULL, module_position INTEGER NOT NULL, position INTEGER NOT NULL, content TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS lessons_course ON lessons(course_id,module_position,position);
CREATE TABLE IF NOT EXISTS enrollments (user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, course_id TEXT NOT NULL REFERENCES courses(id) ON DELETE CASCADE, created_at TEXT NOT NULL, PRIMARY KEY(user_id,course_id));
CREATE INDEX IF NOT EXISTS enrollments_course ON enrollments(course_id);
CREATE TABLE IF NOT EXISTS bookmarks (user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, course_id TEXT NOT NULL REFERENCES courses(id) ON DELETE CASCADE, PRIMARY KEY(user_id,course_id));
CREATE TABLE IF NOT EXISTS progress (user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, lesson_id TEXT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE, completed_at TEXT, last_seen TEXT NOT NULL, PRIMARY KEY(user_id,lesson_id));
CREATE TABLE IF NOT EXISTS notes (user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, lesson_id TEXT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE, body TEXT NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY(user_id,lesson_id));
CREATE TABLE IF NOT EXISTS assignments (id TEXT PRIMARY KEY, course_id TEXT NOT NULL REFERENCES courses(id) ON DELETE CASCADE, title TEXT NOT NULL, instructions TEXT NOT NULL, due_date TEXT);
CREATE TABLE IF NOT EXISTS submissions (id TEXT PRIMARY KEY, assignment_id TEXT NOT NULL REFERENCES assignments(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, body TEXT NOT NULL, repo_url TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'in-review' CHECK(status IN ('in-review','completed')), score INTEGER CHECK(score BETWEEN 0 AND 100), feedback TEXT NOT NULL DEFAULT '', graded_by TEXT REFERENCES users(id), submitted_at TEXT NOT NULL, graded_at TEXT, UNIQUE(assignment_id,user_id));
CREATE TABLE IF NOT EXISTS threads (id TEXT PRIMARY KEY, author_id TEXT NOT NULL REFERENCES users(id), channel TEXT NOT NULL, title TEXT NOT NULL, body TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS replies (id TEXT PRIMARY KEY, thread_id TEXT NOT NULL REFERENCES threads(id) ON DELETE CASCADE, author_id TEXT NOT NULL REFERENCES users(id), body TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS replies_thread ON replies(thread_id,created_at);
CREATE TABLE IF NOT EXISTS votes (thread_id TEXT NOT NULL REFERENCES threads(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, PRIMARY KEY(thread_id,user_id));
CREATE TABLE IF NOT EXISTS certificates (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), course_id TEXT NOT NULL REFERENCES courses(id), issued_at TEXT NOT NULL, UNIQUE(user_id,course_id));
CREATE TABLE IF NOT EXISTS live_classes (id TEXT PRIMARY KEY, course_id TEXT NOT NULL REFERENCES courses(id), host_id TEXT NOT NULL REFERENCES users(id), title TEXT NOT NULL, starts_at TEXT NOT NULL, meeting_url TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS classes_course ON live_classes(course_id,starts_at);
CREATE TABLE IF NOT EXISTS audit_log (id TEXT PRIMARY KEY, actor_id TEXT NOT NULL REFERENCES users(id), action TEXT NOT NULL, target_id TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS attachments (id TEXT PRIMARY KEY, assignment_id TEXT NOT NULL REFERENCES assignments(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id), filename TEXT NOT NULL, content_type TEXT NOT NULL, byte_size INTEGER NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS attachments_assignment_user ON attachments(assignment_id,user_id);
