'use client';
import {useEffect,useState} from 'react';
import {useLearning} from '@/context/LearningContext';
const blank=()=>({title:'',description:'',category:'UI/UX & Design',level:'Beginner',duration:'Self-paced',publication:'draft',modules:[] as any[]});
export default function InstructorPage(){
 const {account,api,refresh}=useLearning();const [overview,setOverview]=useState<any>({courses:[],submissions:[],enrollments:[]});const [editor,setEditor]=useState<any>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [users,setUsers]=useState<any[]>([]);
 async function load(){try{setOverview(await api('instructor/overview'));if(account.role==='admin')setUsers(await api('admin/users'))}catch(error){setError(String(error))}}
 useEffect(()=>{if(account.role!=='learner')void load()},[account.role]);
 async function execute(work:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await work();await load();await refresh();setMessage('Saved successfully.')}catch(error){setError(error instanceof Error?error.message:'Unable to save.')}finally{setBusy(false)}}
 function changeLesson(mi:number,li:number,key:string,value:string){setEditor((previous:any)=>({...previous,modules:previous.modules.map((m:any,i:number)=>i===mi?{...m,lessons:m.lessons.map((l:any,j:number)=>j===li?{...l,[key]:value}:l)}:m)}))}
 if(account.role==='learner')return <section className="surface backend-panel"><h1>Instructor access required</h1><p>An administrator can grant access to teach and manage courses.</p></section>;
 return <div><div className="page-header"><div><h1 className="page-title">Instructor Studio</h1><p className="page-subtitle">Manage your courses and give learners useful feedback.</p></div><button className="btn btn-primary" onClick={()=>setEditor(blank())}>Create course</button></div>{error&&<p className="backend-error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 <div className="backend-grid"><section className="surface backend-panel"><h2>{overview.courses.length} courses</h2><p>{overview.courses.filter((c:any)=>c.publication==='published').length} published</p></section><section className="surface backend-panel"><h2>{new Set(overview.enrollments.map((e:any)=>e.user_id)).size} learners</h2><p>Enrolled in your managed courses</p></section><section className="surface backend-panel"><h2>{overview.submissions.filter((s:any)=>s.status==='in-review').length} submissions</h2><p>Waiting for your feedback</p></section></div>
 {editor&&<section className="surface backend-panel"><h2>{editor.id?'Edit course':'New course draft'}</h2><form className="backend-form" onSubmit={event=>{event.preventDefault();void execute(async()=>{await api('instructor/courses'+(editor.id?'/'+editor.id:''),editor.id?'PUT':'POST',editor);setEditor(null)})}}>
 <label>Course title<input required maxLength={200} value={editor.title} onChange={e=>setEditor({...editor,title:e.target.value})}/></label><label>Description<textarea required maxLength={5000} value={editor.description} onChange={e=>setEditor({...editor,description:e.target.value})}/></label><div className="backend-grid"><label>Category<input required value={editor.category} onChange={e=>setEditor({...editor,category:e.target.value})}/></label><label>Level<select value={editor.level} onChange={e=>setEditor({...editor,level:e.target.value})}>{['Beginner','Intermediate','Advanced'].map(v=><option key={v}>{v}</option>)}</select></label><label>Visibility<select value={editor.publication} onChange={e=>setEditor({...editor,publication:e.target.value})}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label>{account.role==='admin'&&<label>Course owner<select value={editor.ownerId||account.id} onChange={e=>setEditor({...editor,ownerId:e.target.value})}>{users.filter(u=>u.role!=='learner'&&!u.disabled).map(u=><option key={u.id} value={u.id}>{u.name} ({u.email})</option>)}</select></label>}</div>
 {editor.modules.map((module:any,mi:number)=><fieldset className="backend-panel" key={mi} style={{border:'1px solid var(--border-subtle)',borderRadius:10}}><legend>Module {mi+1}</legend><label>Module title<input required value={module.title} onChange={e=>setEditor({...editor,modules:editor.modules.map((m:any,i:number)=>i===mi?{...m,title:e.target.value}:m)})}/></label>{module.lessons.map((lesson:any,li:number)=><div className="backend-form backend-panel" key={lesson.id||li}><h3>Lesson {li+1}</h3><label>Title<input required value={lesson.title} onChange={e=>changeLesson(mi,li,'title',e.target.value)}/></label><div className="backend-grid"><label>Format<select value={lesson.type} onChange={e=>changeLesson(mi,li,'type',e.target.value)}><option value="reading">Reading</option><option value="video">Video</option><option value="assignment">Practice</option></select></label><label>Duration<input required value={lesson.duration} onChange={e=>changeLesson(mi,li,'duration',e.target.value)}/></label></div>{lesson.type==='video'&&<label>Hosted video URL<input type="url" required value={lesson.videoUrl||''} onChange={e=>changeLesson(mi,li,'videoUrl',e.target.value)}/></label>}<label>Lesson content<textarea value={lesson.overview||''} onChange={e=>changeLesson(mi,li,'overview',e.target.value)}/></label><label>Practice prompt<textarea value={lesson.exercise||''} onChange={e=>changeLesson(mi,li,'exercise',e.target.value)}/></label></div>)}<button className="btn btn-secondary" type="button" onClick={()=>setEditor({...editor,modules:editor.modules.map((m:any,i:number)=>i===mi?{...m,lessons:[...m.lessons,{title:'',duration:'10m',type:'reading',overview:'',exercise:''}]}:m)})}>Add lesson</button></fieldset>)}
 <div className="backend-actions"><button className="btn btn-secondary" type="button" onClick={()=>setEditor({...editor,modules:[...editor.modules,{title:'',lessons:[]}]})}>Add module</button><button className="btn btn-primary" disabled={busy}>Save course</button><button type="button" className="btn btn-secondary" onClick={()=>setEditor(null)}>Cancel</button></div></form></section>}
 <section className="surface backend-panel"><h2>Your courses</h2>{overview.courses.length===0&&<p>Create your first course to get started.</p>}{overview.courses.map((course:any)=><div className="backend-row" key={course.id}><div><strong>{course.title}</strong><p>{course.publication} · {course.enrollmentCount} enrolled · {course.modules.length} modules</p></div><button className="btn btn-secondary" onClick={()=>setEditor(structuredClone(course))}>Edit course</button></div>)}</section>
 <section className="surface backend-panel"><h2>Create an assignment</h2><form className="backend-form" onSubmit={event=>{event.preventDefault();const form=event.currentTarget;const values=Object.fromEntries(new FormData(form));void execute(async()=>{await api('instructor/assignments','POST',values);form.reset()})}}><label>Course<select name="courseId" required><option value="">Choose a course</option>{overview.courses.map((c:any)=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Title<input name="title" required maxLength={200}/></label><label>Instructions<textarea name="instructions" required maxLength={15000}/></label><label>Due date (optional)<input type="date" name="dueDate"/></label><button className="btn btn-primary" disabled={busy}>Create assignment</button></form></section>
 <section className="surface backend-panel"><h2>Submissions & feedback</h2>{overview.submissions.length===0&&<p>No submissions yet.</p>}{overview.submissions.map((submission:any)=><article key={submission.id} className="backend-panel"><h3>{submission.title} — {submission.name}</h3><pre>{submission.body}</pre>{submission.attachments?.map((file:any)=><a className="text-link" key={file.id} href={"/api/files/"+file.id}>{file.filename}</a>)}{submission.repo_url&&<a href={submission.repo_url} target="_blank" rel="noopener noreferrer" className="text-link">Open submission link</a>}{submission.status==='completed'?<p>Grade: {submission.score}/100 · {submission.feedback}</p>:<form className="backend-form" onSubmit={event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));void execute(async()=>{await api('instructor/submissions/'+submission.id,'PATCH',{score:Number(values.score),feedback:values.feedback})})}}><label>Score / 100<input name="score" type="number" min={0} max={100} required/></label><label>Feedback<textarea name="feedback" required maxLength={10000}/></label><button className="btn btn-primary" disabled={busy}>Save grade & feedback</button></form>}</article>)}</section>
 <section className="surface backend-panel"><h2>Schedule a live class</h2><form className="backend-form" onSubmit={event=>{event.preventDefault();const form=event.currentTarget;const values=Object.fromEntries(new FormData(form));void execute(async()=>{await api('instructor/live-classes','POST',{...values,startsAt:new Date(values.startsAt as string).toISOString()});form.reset()})}}><label>Course<select name="courseId" required><option value="">Choose a course</option>{overview.courses.map((c:any)=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Title<input name="title" required/></label><label>Start time (your local time)<input type="datetime-local" name="startsAt" required/></label><label>Meeting URL<input type="url" name="meetingUrl" required/></label><button className="btn btn-primary" disabled={busy}>Schedule class</button></form></section>
 <section className="surface backend-panel"><h2>Enrolled learners</h2>{overview.enrollments.map((enrollment:any)=><div className="backend-row" key={enrollment.user_id+enrollment.course_id}><span>{enrollment.name} · {enrollment.email}</span><span>{overview.courses.find((c:any)=>c.id===enrollment.course_id)?.title}</span></div>)}</section></div>;
}
