/* Authored sample curriculum for the frontend learning experience. */
(() => {
  const guides = {
    'course-101': {
      role: 'Design systems educator', requirements: ['Comfort with HTML and CSS', 'A code editor and a small interface to improve'],
      outcomes: ['Build a reusable design token system', 'Create layouts that adapt to their container', 'Use motion and focus states with intention', 'Document and test a resilient component'],
      topics: [
        ['Design token architecture', 'Separate primitive values from semantic roles. A primitive such as violet-600 describes a color; a semantic token such as action-primary describes its purpose. Components should depend on semantic tokens so a theme can change without rewriting component styles.', 'Choose three recurring colors in an interface. Give each a semantic role and map that role to a primitive value.'],
        ['Fluid typography', 'A readable type scale needs more than a large heading. Set a comfortable body size, line height, and text measure first. Use clamp() to keep fluid sizes within deliberate minimum and maximum values, then check the layout at both extremes.', 'Write a heading rule using clamp(). Compare a short heading and a long heading at narrow and wide widths.'],
        ['Container queries & modern grids', 'Viewport breakpoints describe the browser, while container queries describe the space available to a component. Establish container-type: inline-size on a parent wrapper. Inside @container, change the child layout only when its content has enough room. The queried container cannot query itself to change its own size.', 'Create a card inside a named container. Start with a stacked layout, then change its inner grid to two columns above 30rem.'],
        ['Subgrid & alignment', 'Subgrid lets nested elements participate in their parent grid tracks. It is useful when cards with different amounts of content need aligned headings, descriptions, and actions. Start with explicit parent tracks and keep a normal grid fallback for contexts where subgrid is unnecessary.', 'Compare two cards with different title lengths. Align their action rows using the parent grid.'],
        ['Resilient card components', 'A component is resilient when content changes do not break its layout. Test long labels, missing images, translated text, keyboard focus, and a narrow container. Prefer content-driven height and flexible tracks over fixed dimensions.', 'Build one card and test five edge cases. Record the change that made the largest improvement.'],
        ['View transitions', 'A transition should help a learner understand what changed. Keep navigation usable when transitions are unavailable or disabled. Respect prefers-reduced-motion and avoid animation that delays interaction or masks a loading state.', 'Describe one state change that benefits from motion and one that should happen immediately.'],
        ['Scroll-driven motion', 'Scroll-linked effects connect progress to movement through a page. Keep essential information visible without the effect. Test the layout without animation, then add motion as a progressive enhancement with a reduced-motion alternative.', 'Sketch a reading progress indicator. Explain how its meaning remains available without animation.']
      ]
    },
    'course-102': {role:'Software architecture educator',requirements:['Working knowledge of JavaScript','Familiarity with HTTP requests'],outcomes:['Separate model calls from product logic','Design a streaming interface','Handle validation and failure states'],topics:[['Structured model outputs','Treat model output as untrusted input. Define a schema, validate the response, and handle incomplete or invalid fields before using them in application logic. Keep tool permissions narrow and make important actions reviewable.','Sketch a response schema for a study planner and list three invalid outputs to reject.'],['Streaming interface states','A stream can start, produce partial results, stall, or end with an error. Model these as explicit UI states. Preserve already received content, provide a retry path, and avoid treating a disconnected stream as a complete response.','Draw the idle, loading, streaming, completed, and error states of a chat response.'],['Design a resilient learning assistant','Separate retrieval, generation, and display so each boundary can be tested. Give the interface a clear fallback when context is missing. Capture only the minimum operational data needed to diagnose failures.','Write an acceptance checklist for a response that cites unavailable course material.']]},
    'course-103': {role:'Distributed systems educator',requirements:['Basic service architecture knowledge'],outcomes:['Identify failure boundaries','Choose consistency tradeoffs','Design a retry strategy'],topics:[['Events and boundaries','An event describes something that has already happened. Define its owner, identifier, version, and expected consumers. Assume that delivery may be repeated and design consumers to process the same event safely.','Design an enrollment-created event and explain how a consumer avoids duplicates.'],['Consistency tradeoffs','Different operations tolerate different amounts of delay. A progress dashboard can often show slightly delayed data; a permission decision needs a more precise rule. Document the consistency requirement before choosing a storage pattern.','Compare the consistency needs of lesson progress and course access.'],['Failure and recovery','Retries should have limits, backoff, and clear ownership. A failing dependency must not consume unlimited resources. Plan recovery from partial success and make pending work observable.','Draw the recovery path when a certificate job fails after course completion.']]},
    'course-104': {role:'Product strategy educator',requirements:['An example product to study'],outcomes:['Define a useful outcome metric','Frame an experiment','Balance growth and usability'],topics:[['Choosing an outcome','An outcome describes a change for the user. Start with the behavior that signals value, then define a measurable proxy and its limitations. A single metric rarely captures quality by itself.','Define an outcome for a learner completing their first useful lesson.'],['Experiment design','Write a hypothesis before changing the interface. Define the audience, success signal, guardrail metrics, and a decision rule. Consider what would make the result misleading.','Write a hypothesis for a simpler course enrollment flow.'],['Interpreting results','A change in a metric is evidence, not a complete explanation. Look for differences across cohorts and check whether the measurement itself changed. Pair quantitative signals with observed user behavior.','List two alternative explanations for an increase in lesson completions.']]},
    'course-105': {role:'TypeScript educator',requirements:['Comfort writing JavaScript'],outcomes:['Model states explicitly','Narrow unknown values safely','Design a predictable SDK'],topics:[['Modeling states','A discriminated union makes allowed states explicit. Put fields on the state that owns them rather than making every field optional. This makes invalid combinations harder to represent.','Model a lesson request as idle, loading, success, or error.'],['Validating boundaries','Type annotations do not validate network responses at runtime. Accept unknown input at external boundaries and narrow it after checking its structure. Keep validation errors understandable.','Write a guard for an object with a string lesson identifier.'],['SDK ergonomics','A useful SDK has predictable errors, clear inputs, and stable return shapes. Prefer examples that show the entire request lifecycle, including cancellation and failure.','Draft the public signature and usage example for fetching a course.']]},
    'course-106': {role:'User research educator',requirements:['A product question you want to explore'],outcomes:['Write unbiased research questions','Plan a focused interview','Turn observations into insights'],topics:[['Start with a question','A useful research question names an uncertainty, not a preferred solution. Ask how learners currently find the right lesson before asking whether they want a new recommendation feature.','Rewrite a feature request as two open research questions.'],['Listen for behavior','Ask participants about a recent specific experience. Invite them to describe what happened, what they tried, and where they got stuck. Avoid questions that suggest the answer you hope to hear.','Prepare five neutral questions about a recent learning experience.'],['Synthesize evidence','Separate observations from interpretations. Group repeated patterns, retain contradictory evidence, and state the limits of your sample. An insight should connect an observed need to a possible opportunity.','Turn three interview observations into one tentative insight.']]},
    'course-107': {role:'Brand design educator',requirements:['A brand or personal project to explore'],outcomes:['Define a visual direction','Create a typography hierarchy','Apply a consistent identity'],topics:[['Find the visual direction','Translate brand attributes into concrete design choices. A word such as calm can influence spacing, color contrast, and image treatment. Compare directions using the same content so the differences are meaningful.','Choose three brand attributes and a visual decision for each.'],['Typography and color','Build hierarchy with size, weight, and spacing before adding more typefaces. Assign colors to roles and check that important text remains readable in its actual context.','Create a heading, body, and caption style for one small brand card.'],['Make an identity repeatable','Document a few useful rules and show them in real examples. Include a small layout, a dense layout, and a constrained format to reveal where the system needs flexibility.','Apply your identity to a card and a narrow banner. Explain what stays consistent.']]},
    'course-108': {role:'Product thinking educator',requirements:['Curiosity about product decisions'],outcomes:['Frame user problems','Compare opportunities','Write a small, testable next step'],topics:[['Frame the problem','Describe who is affected, what they are trying to do, and what prevents progress. Keep assumptions visible. A strong problem statement leaves room for more than one solution.','Write a problem statement for a learner returning after a long break.'],['Prioritize opportunities','Compare expected user value, confidence in the evidence, and effort. A score is a conversation aid, not a substitute for judgment. Make dependencies and uncertainty explicit.','Compare two possible improvements and explain the tradeoff.'],['Take a small next step','Choose the smallest change that can reduce an important uncertainty. Define what you will observe and what you would do next if the result differs from your expectation.','Write a one-week experiment with an observable success signal.']]}
  };
  window.LMSData.courses.forEach(course => {
    const guide = guides[course.id];
    course.outcomes = guide.outcomes;
    course.requirements = guide.requirements;
    course.instructorRole = guide.role;
    if (!course.modules?.length) course.modules = [{title:'Foundations & guided practice',lessons:guide.topics.map((topic,index)=>({id:`${course.id}-lesson-${index+1}`,title:topic[0],duration:'8m',type:'reading',completed:course.status==='completed'}))}];
    if (course.id === 'course-102') course.modules.push({title:'Applied architecture',lessons:[{id:'les-203',title:'Design a resilient learning assistant',duration:'12m',type:'assignment',completed:false}]});
    course.modules.flatMap(module=>module.lessons).forEach((lesson,index)=>{
      const topic = guide.topics[index % guide.topics.length];
      lesson.overview = topic[1];
      lesson.exercise = topic[2];
      lesson.takeaways = guide.outcomes;
      // Previous videos were unrelated stock clips. Lessons use authored sample readings.
      delete lesson.videoUrl;
      if (lesson.type !== 'assignment') lesson.type = 'reading';
    });
  });
})();
