'use client';
import {useEffect,useState} from 'react';
import {useLearning} from '@/context/LearningContext';
export default function Administration(){const {account,api}=useLearning();const [users,setUsers]=useState<any[]>([]);const [audit,setAudit]=useState<any[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function load(){try{const [people,events]=await Promise.all([api('admin/users'),api('admin/audit')]);setUsers(people);setAudit(events)}catch(error){setError(String(error))}}
 useEffect(()=>{if(account.role==='admin')void load()},[account.role]);
 async function update(id:string,values:unknown){setBusy(true);setError('');try{await api('admin/users/'+id,'PATCH',values);await load()}catch(error){setError(String(error))}finally{setBusy(false)}}
 if(account.role!=='admin')return <section className="surface backend-panel"><h1>Administrator access required</h1></section>;
 return <div><h1 className="page-title">Academy Administration</h1><p className="page-subtitle">Manage roles and account access. Role changes end the affected user’s existing sessions.</p>{error&&<p role="alert" className="backend-error">{error}</p>}<section className="surface backend-panel"><h2>{users.length} accounts</h2>{users.map(user=><div className="backend-row" key={user.id}><div><strong>{user.name}</strong><p>{user.email}</p></div><label className="backend-form">Role<select aria-label={'Role for '+user.name} value={user.role} disabled={busy||user.id===account.id} onChange={e=>void update(user.id,{role:e.target.value})}>{['learner','instructor','admin'].map(role=><option key={role}>{role}</option>)}</select></label><button className="btn btn-secondary" disabled={busy||user.id===account.id} onClick={()=>void update(user.id,{disabled:!user.disabled})}>{user.disabled?'Enable account':'Disable account'}</button></div>)}</section><section className="surface backend-panel"><h2>Recent administrative activity</h2>{audit.length===0&&<p>No administrative changes yet.</p>}{audit.map(event=><div className="backend-row" key={event.id}><span>{event.name} · {event.action}</span><time>{new Date(event.created_at).toLocaleString()}</time></div>)}</section></div>}
