import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {createHmac} from 'node:crypto';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {openDatabase} from '../server/database.mjs';
import {createService} from '../server/service.mjs';
const seed=[{id:'c1',title:'Test course',description:'A useful course',category:'Design',level:'Beginner',duration:'20m',thumbnail:'',art:'violet',symbol:'book-open',rating:0,modules:[{title:'First module',lessons:[{id:'l1',title:'First',duration:'10m',type:'reading',overview:'Private lesson content',completed:true},{id:'l2',title:'Second',duration:'10m',type:'reading',completed:false}]}]}];
function client(service){let cookie='';return {async request(path,method='GET',body,origin='http://localhost'){const res=await service.handle(new Request('http://localhost/api/'+path,{method,headers:{cookie,origin,...(body!==undefined?{'content-type':'application/json'}:{})},body:body===undefined?undefined:JSON.stringify(body)}));if(res.headers.has('set-cookie'))cookie=res.headers.get('set-cookie').split(';')[0];return {status:res.status,headers:res.headers,body:res.headers.get('content-type')?.includes('json')?await res.json():await res.text()}}}}
async function fixture(t,options={}){const db=openDatabase(':memory:');t.after(()=>db.close());const service=createService(db,seed,{setupToken:'private-setup-token',origin:'http://localhost',mail:{send:async()=>{}},...options});const admin=client(service),learner=client(service),other=client(service),teacher=client(service);const password='a long strong test password';let result=await admin.request('auth/setup','POST',{name:'Admin',email:'admin@example.com',password,setupToken:'private-setup-token'});assert.equal(result.status,200);for(const [c,name]of [[learner,'learner'],[other,'other'],[teacher,'teacher']]){result=await c.request('auth/register','POST',{name,email:name+'@example.com',password,role:'admin'});assert.equal(result.status,200);assert.equal(result.body.user.role,'learner')}const users=(await admin.request('admin/users')).body;const teacherId=users.find(u=>u.email==='teacher@example.com').id;await admin.request('admin/users/'+teacherId,'PATCH',{role:'instructor'});await admin.request('admin/users/'+teacherId+'/instructor-approval','PATCH',{status:'approved'});assert.equal((await teacher.request('workspace')).status,401);await teacher.request('auth/login','POST',{email:'teacher@example.com',password});return {db,service,admin,learner,other,teacher,users,password,teacherId}}
test('Authentication, CSRF, role escalation and session invalidation',async t=>{const f=await fixture(t);assert.equal((await client(f.service).request('workspace')).status,401);assert.equal((await f.learner.request('admin/users')).status,403);assert.equal((await f.learner.request('instructor/overview')).status,403);assert.equal((await f.learner.request('courses/c1/enrollment','POST',{},'https://attacker.example')).status,403);assert.equal((await f.admin.request('auth/setup','POST',{name:'evil',email:'evil@example.com',password:f.password,setupToken:'private-setup-token'})).status,409);await f.learner.request('auth/logout','POST',{});assert.equal((await f.learner.request('workspace')).status,401)});
test('Custom permissions require explicit assignment and cannot self-escalate',async t=>{const f=await fixture(t);const roles=(await f.admin.request('admin/roles')).body;assert.ok(roles.permissions.includes('manage_users'));assert.equal((await f.learner.request('admin/roles')).status,403);const created=await f.admin.request('admin/roles','POST',{name:'Support Staff',permissions:['manage_users']});assert.equal(created.status,201);const learnerId=f.users.find(u=>u.email==='learner@example.com').id;assert.equal((await f.admin.request('admin/users/'+learnerId+'/roles','PUT',{roleIds:[created.body.id]})).status,200);assert.equal((await f.learner.request('admin/users')).status,401);await f.learner.request('auth/login','POST',{email:'learner@example.com',password:f.password});assert.equal((await f.learner.request('admin/users')).status,200);assert.equal((await f.learner.request('admin/roles')).status,403);assert.equal((await f.learner.request('admin/users/'+learnerId,'PATCH',{role:'admin'})).status,403);assert.equal((await f.learner.request('admin/users/'+learnerId+'/roles','PUT',{roleIds:['admin']})).status,403);assert.equal((await f.admin.request('admin/roles/'+created.body.id,'PATCH',{permissions:[]})).status,200);assert.equal((await f.learner.request('admin/users')).status,401);await f.learner.request('auth/login','POST',{email:'learner@example.com',password:f.password});assert.equal((await f.learner.request('admin/users')).status,403)});
test('Admin overview counts authoritative records and excludes private account access',async t=>{const f=await fixture(t);assert.equal((await f.learner.request('admin/overview')).status,403);const summary=(await f.admin.request('admin/overview')).body;assert.equal(summary.students,2);assert.equal(summary.instructors,1);assert.equal(summary.courses,1);assert.equal(summary.activeCourses,1);assert.equal(summary.enrollments,0);await f.learner.request('courses/c1/enrollment','POST',{});const updated=(await f.admin.request('admin/overview')).body;assert.equal(updated.enrollments,1);assert.equal(updated.recentEnrollments[0].student,'learner')});
test('Administrators can edit user identity and only delete accounts without history',async t=>{const f=await fixture(t);const learnerId=f.users.find(u=>u.email==='learner@example.com').id;const otherId=f.users.find(u=>u.email==='other@example.com').id;const adminId=f.users.find(u=>u.email==='admin@example.com').id;let response=await f.admin.request('admin/users/'+learnerId,'PATCH',{name:'Updated Learner',email:'updated@example.com'});assert.equal(response.status,200);assert.equal((await f.learner.request('workspace')).status,401,'identity edits revoke existing sessions');await f.learner.request('auth/login','POST',{email:'updated@example.com',password:f.password});const edited=(await f.admin.request('admin/users')).body.find(u=>u.id===learnerId);assert.equal(edited.name,'Updated Learner');assert.ok(edited.createdAt);assert.equal((await f.admin.request('admin/users/'+learnerId,'PATCH',{email:'admin@example.com'})).status,409,'email addresses remain unique');assert.equal((await f.admin.request('admin/users/'+otherId,'DELETE')).status,200);assert.equal((await f.other.request('auth/login','POST',{email:'other@example.com',password:f.password})).status,401);await f.learner.request('courses/c1/enrollment','POST',{});assert.equal((await f.admin.request('admin/users/'+learnerId,'DELETE')).status,409,'learning history must be preserved');assert.equal((await f.admin.request('admin/users/'+adminId,'DELETE')).status,409,'the current administrator cannot delete their own account')});
test('Course metadata is validated and disabled certificates are not issued',async t=>{const f=await fixture(t);const payload={title:'Accessible interfaces',subtitle:'Practical UI patterns',description:'Build accessible components.',category:'Design',level:'Beginner',duration:'2h',language:'English',targetAudience:'Designers',promotionalVideo:'https://example.com/intro',certificateEnabled:false,outcomes:['Build a card'],requirements:['HTML basics'],publication:'published',modules:[{title:'Start',lessons:[{title:'Introduction',duration:'10m',type:'reading',overview:'Read this.'}]}]};let response=await f.teacher.request('instructor/courses','POST',payload);assert.equal(response.status,201);const id=response.body.id;const course=(await f.teacher.request('instructor/overview')).body.courses.find(item=>item.id===id);assert.equal(course.subtitle,payload.subtitle);assert.equal(course.certificateEnabled,false);assert.deepEqual(course.outcomes,payload.outcomes);assert.equal((await f.teacher.request('instructor/courses/'+id,'PUT',{...payload,promotionalVideo:'http://unsafe.example'})).status,400);await f.learner.request('courses/'+id+'/enrollment','POST',{});const lessonId=course.modules[0].lessons[0].id;await f.learner.request('lessons/'+lessonId+'/progress','PUT',{completed:true});assert.equal((await f.db.get('SELECT COUNT(*) AS count FROM certificates WHERE course_id=?',[id])).count,0)});
test('Learner enrollment, private content, progress and notes cannot cross accounts',async t=>{const f=await fixture(t);let state=(await f.learner.request('workspace')).body;assert.equal(state.enrolledCourses.length,0);assert.equal(state.courses[0].modules[0].lessons[0].overview,undefined);assert.equal(state.courses[0].progress,0);assert.equal((await f.learner.request('lessons/l1/note','PUT',{note:'secret'})).status,403);await f.learner.request('courses/c1/enrollment','POST',{});await f.learner.request('lessons/l1/note','PUT',{note:'  secret\n'});await f.learner.request('lessons/l1/progress','PUT',{completed:true});state=(await f.learner.request('workspace')).body;assert.equal(state.userNotes.l1,'  secret\n');assert.equal(state.courses[0].progress,50);assert.equal((await f.other.request('workspace')).body.userNotes.l1,undefined);assert.equal((await f.other.request('lessons/l1/resource')).status,403);assert.ok((await f.learner.request('lessons/l1/resource')).body.includes('Private lesson content'));await f.learner.request('lessons/l2/progress','PUT',{completed:true});await f.learner.request('lessons/l2/progress','PUT',{completed:true});state=(await f.learner.request('workspace')).body;assert.equal(state.courses[0].progress,100);assert.equal(state.certificates.length,1);assert.equal((await f.other.request('certificates/'+state.certificates[0].id)).status,403)});
test('Instructor ownership, draft visibility, publication and protected lesson edits',async t=>{const f=await fixture(t);assert.equal((await f.teacher.request('instructor/courses/c1','PUT',{title:'Stolen'})).status,403);const draft=await f.teacher.request('instructor/courses','POST',{title:'My draft',category:'Design',description:'A draft',modules:[{title:'Start',lessons:[{title:'Intro',type:'reading',overview:'hello'}]}]});assert.equal(draft.status,201);assert.equal((await f.learner.request('workspace')).body.courses.length,1);assert.equal((await f.learner.request('courses/'+draft.body.id+'/enrollment','POST',{})).status,404);await f.teacher.request('instructor/courses/'+draft.body.id,'PUT',{publication:'published'});const published=(await f.learner.request('workspace')).body.courses.find(c=>c.id===draft.body.id);assert.ok(published);await f.learner.request('courses/'+draft.body.id+'/enrollment','POST',{});const id=published.modules[0].lessons[0].id;await f.learner.request('lessons/'+id+'/note','PUT',{note:'My work'});assert.equal((await f.teacher.request('instructor/courses/'+draft.body.id,'PUT',{modules:[],publication:'draft'})).status,409);assert.equal((await f.learner.request('workspace')).body.courses.find(c=>c.id===draft.body.id).publication,'published')});
test('Submission grading requires course ownership and certificates wait for passing grades',async t=>{const f=await fixture(t);const a=await f.admin.request('instructor/assignments','POST',{courseId:'c1',title:'Practice',instructions:'Show your work'});assert.equal(a.status,201);await f.learner.request('courses/c1/enrollment','POST',{});for(const id of ['l1','l2'])await f.learner.request('lessons/'+id+'/progress','PUT',{completed:true});assert.equal((await f.learner.request('workspace')).body.certificates.length,0);assert.equal((await f.other.request('assignments/'+a.body.id+'/submission','PUT',{body:'intrusion'})).status,403);assert.equal((await f.learner.request('assignments/'+a.body.id+'/submission','PUT',{body:'my work',repoUrl:'https://example.com/work'})).status,200);const submission=(await f.admin.request('instructor/overview')).body.submissions[0];assert.equal((await f.teacher.request('instructor/submissions/'+submission.id,'PATCH',{score:90,feedback:'Great'})).status,403);assert.equal((await f.admin.request('instructor/submissions/'+submission.id,'PATCH',{score:101,feedback:'Invalid'})).status,400);assert.equal((await f.admin.request('instructor/submissions/'+submission.id,'PATCH',{score:90,feedback:'Great work'})).status,200);const state=(await f.learner.request('workspace')).body;assert.equal(state.assignments[0].score,'90/100');assert.equal(state.certificates.length,1)});
test('Profile input cannot grant roles; account disabling ends sessions',async t=>{const f=await fixture(t);await f.learner.request('profile','PATCH',{name:'Updated',role:'admin'});assert.equal((await f.learner.request('auth/session')).body.user.role,'learner');const user=f.users.find(u=>u.email==='learner@example.com');await f.admin.request('admin/users/'+user.id,'PATCH',{disabled:true});assert.equal((await f.learner.request('workspace')).status,401);assert.equal((await f.learner.request('auth/login','POST',{email:user.email,password:f.password})).status,401)});
test('Discussion votes are unique and replies persist',async t=>{const f=await fixture(t);await f.learner.request('threads','POST',{channel:'#ui-ux-design',title:'Question',content:'How does this work?'});const id=(await f.learner.request('workspace')).body.communityThreads[0].id;await f.other.request('threads/'+id+'/vote','PUT',{});await f.other.request('threads/'+id+'/vote','PUT',{});await f.other.request('threads/'+id+'/replies','POST',{content:'Try a small example.'});assert.equal((await f.learner.request('workspace')).body.communityThreads[0].upvotes,1);assert.equal((await f.learner.request('threads/'+id+'/replies')).body.length,1);assert.equal((await f.other.request('threads/'+id,'DELETE')).status,403)});
test('Records persist after closing and reopening the database',async t=>{const dir=mkdtempSync(join(tmpdir(),'lms-persistence-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const file=join(dir,'test.sqlite');let db=openDatabase(file);let service=createService(db,seed,{});let user=client(service);const values={name:'Persistent',email:'persist@example.com',password:'persistent long password'};await user.request('auth/register','POST',values);await user.request('courses/c1/enrollment','POST',{});await user.request('lessons/l1/note','PUT',{note:'Keep this'});db.close();db=openDatabase(file);t.after(()=>db.close());service=createService(db,seed,{});user=client(service);await user.request('auth/login','POST',values);assert.equal((await user.request('workspace')).body.userNotes.l1,'Keep this')});
test('Passwords are hashed, expired sessions are rejected, password changes revoke sessions',async t=>{const f=await fixture(t);const record=await f.db.get('SELECT password_hash FROM users WHERE email=?',['learner@example.com']);assert.ok(record.password_hash.startsWith('scrypt:'));assert.ok(!record.password_hash.includes(f.password));assert.equal((await f.learner.request('auth/password','POST',{currentPassword:'incorrect password',password:'new password long enough'})).status,401);assert.equal((await f.learner.request('auth/password','POST',{currentPassword:f.password,password:'new password long enough'})).status,200);assert.equal((await f.learner.request('workspace')).status,401);assert.equal((await f.learner.request('auth/login','POST',{email:'learner@example.com',password:'new password long enough'})).status,200);await f.db.run('UPDATE sessions SET expires_at=0');assert.equal((await f.learner.request('workspace')).status,401)});
test('Registration sends a 6-digit verification code by email, and codes are single-use',async t=>{
  const db=openDatabase(':memory:');t.after(()=>db.close());const sent=[];
  const service=createService(db,seed,{setupToken:'private-setup-token',origin:'http://localhost',mail:{send:async message=>{sent.push(message)}}});
  const user=client(service);const password='a long strong test password';
  await user.request('auth/register','POST',{name:'Learner',email:'verify@example.com',password});
  assert.equal(sent.length,1);assert.match(sent[0].subject,/Verify/);
  assert.ok(sent[0].html.includes('Verify your email address'),'a styled HTML alternative is included');
  assert.equal((await user.request('auth/session')).body.user.emailVerified,false);
  const code=sent[0].text.match(/\n\n(\d{6})\n\n/)[1];
  const wrongCode=(Number(code[0])+1)%10+code.slice(1);
  assert.equal((await user.request('auth/verify-email','POST',{code:wrongCode})).status,400);
  assert.equal((await user.request('auth/verify-email','POST',{code})).status,200);
  assert.equal((await user.request('auth/session')).body.user.emailVerified,true);
  assert.equal((await user.request('auth/verify-email','POST',{code})).status,200,'once verified, re-submitting is a harmless no-op');
  assert.equal((await user.request('auth/resend-verification','POST',{})).status,409);
});
test('Password reset never reveals which emails exist and consumes its token once',async t=>{
  const db=openDatabase(':memory:');t.after(()=>db.close());const sent=[];
  const service=createService(db,seed,{setupToken:'private-setup-token',origin:'http://localhost',mail:{send:async message=>{sent.push(message)}}});
  const user=client(service);const password='a long strong test password';
  await user.request('auth/register','POST',{name:'Learner',email:'reset@example.com',password});
  sent.length=0;
  assert.equal((await user.request('auth/reset-request','POST',{email:'nobody@example.com'})).status,200);
  assert.equal(sent.length,0,'no email is sent for an unknown address');
  assert.equal((await user.request('auth/reset-request','POST',{email:'reset@example.com'})).status,200);
  assert.equal(sent.length,1);assert.match(sent[0].subject,/Reset/);
  const resetToken=sent[0].text.match(/reset-password\?token=([a-f0-9]+)/)[1];
  assert.equal((await user.request('auth/reset','POST',{token:resetToken,password:'too short'})).status,400);
  assert.equal((await user.request('auth/reset','POST',{token:'bogus-token',password:'a brand new long password'})).status,400);
  assert.equal((await user.request('workspace')).status,200,'the old session is unaffected until the reset succeeds');
  assert.equal((await user.request('auth/reset','POST',{token:resetToken,password:'a brand new long password'})).status,200);
  assert.equal((await user.request('workspace')).status,401,'resetting the password revokes existing sessions');
  assert.equal((await user.request('auth/login','POST',{email:'reset@example.com',password:'a brand new long password'})).status,200);
  assert.equal((await user.request('auth/reset','POST',{token:resetToken,password:'yet another long password'})).status,400,'reset tokens are single-use');
});
test('Stripe checkout and subscription lifecycle enforce paid access without changing roles',async t=>{
  let checkoutBody='';const webhookSecret='whsec_test_secret';
  const stripe={enabled:true,secretKey:'sk_test_example',webhookSecret,prices:{'pro-monthly':'price_month','pro-yearly':'price_year'},fetch:async(url,init)=>{if(url.includes('/prices/'))return new Response(JSON.stringify({active:true,unit_amount:18000,currency:'gbp',recurring:{interval:url.endsWith('price_year')?'year':'month',interval_count:1}}),{status:200});checkoutBody=String(init.body);return new Response(JSON.stringify({url:'https://checkout.stripe.com/test-session'}),{status:200,headers:{'content-type':'application/json'}})}};
  const f=await fixture(t,{stripe});
  const learnerId=f.users.find(user=>user.email==='learner@example.com').id;
  const draft=await f.admin.request('instructor/courses','POST',{title:'Paid course',description:'Members only',category:'Design',access:'pro',publication:'published',modules:[{title:'Start',lessons:[{title:'Welcome',type:'reading',duration:'10m'}]}]});
  assert.equal((await f.learner.request('courses/'+draft.body.id+'/enrollment','POST',{})).status,402);
  const checkout=await f.learner.request('billing/checkout','POST',{plan:'pro-yearly',price:'price_attacker'});
  assert.equal(checkout.status,200);assert.equal(checkout.body.url,'https://checkout.stripe.com/test-session');assert.match(checkoutBody,/price_year/);assert.doesNotMatch(checkoutBody,/price_attacker/);
  assert.equal((await f.learner.request('billing/plans')).body.plans.length,2);
  const event={id:'evt_checkout_1',type:'checkout.session.completed',data:{object:{client_reference_id:learnerId,customer:'cus_learner',subscription:'sub_learner',metadata:{user_id:learnerId,plan_key:'pro-yearly'}}}};
  const send=(payload)=>{const raw=JSON.stringify(payload);const timestamp=Math.floor(Date.now()/1000);const signature=createHmac('sha256',webhookSecret).update(timestamp+'.'+raw).digest('hex');return f.service.handle(new Request('http://localhost/api/billing/webhook',{method:'POST',headers:{'stripe-signature':`t=${timestamp},v1=${signature}`},body:raw}))};
  assert.equal((await send(event)).status,200);assert.equal((await send(event)).status,200);
  assert.equal((await f.learner.request('workspace')).body.billing.plan,'free','Checkout completion alone cannot grant access');
  const future=Math.floor(Date.now()/1000)+86400;
  const subscription={id:'evt_subscription_active',created:100,type:'customer.subscription.updated',data:{object:{id:'sub_learner',customer:'cus_learner',status:'active',current_period_end:future,items:{data:[{price:{id:'price_year'}}]},metadata:{user_id:learnerId}}}};
  assert.equal((await send(subscription)).status,200);
  const workspace=(await f.learner.request('workspace')).body;assert.equal(workspace.billing.plan,'pro');assert.equal(workspace.user.role,'learner');
  assert.equal((await f.learner.request('courses/'+draft.body.id+'/enrollment','POST',{})).status,200);
  const lessonId=workspace.courses.find(course=>course.id===draft.body.id).modules[0].lessons[0].id;
  assert.equal((await f.learner.request('lessons/'+lessonId+'/resource')).status,200);
  await f.db.run('UPDATE subscriptions SET current_period_end=? WHERE user_id=?',[new Date(Date.now()-60000).toISOString(),learnerId]);
  assert.equal((await f.learner.request('lessons/'+lessonId+'/resource')).status,402,'a stale active webhook cannot extend an expired period forever');
  await f.db.run('UPDATE subscriptions SET current_period_end=? WHERE user_id=?',[new Date(future*1000).toISOString(),learnerId]);
  const canceled={...subscription,id:'evt_subscription_canceled',created:200,type:'customer.subscription.deleted',data:{object:{...subscription.data.object,status:'canceled'}}};
  assert.equal((await send(canceled)).status,200);
  assert.equal((await f.learner.request('workspace')).body.billing.plan,'free');
  assert.equal((await f.learner.request('lessons/'+lessonId+'/resource')).status,402,'an existing enrollment cannot bypass expired paid access');
  const locked=(await f.learner.request('workspace')).body.courses.find(course=>course.id===draft.body.id);
  assert.equal(locked.modules[0].lessons[0].overview,undefined,'the workspace omits paid lesson content after cancellation');
  assert.equal((await send(subscription)).status,200,'an older event is accepted but cannot restore access');
  assert.equal((await f.learner.request('workspace')).body.billing.plan,'free');
  const unknown={...subscription,id:'evt_subscription_unknown_price',created:300,data:{object:{...subscription.data.object,items:{data:[{price:{id:'price_other_product'}}]}}}};
  assert.equal((await send(unknown)).status,200);
  assert.equal((await f.learner.request('workspace')).body.billing.plan,'free','an unrecognized price cannot grant Pro');
  const events=await f.db.get('SELECT COUNT(*) AS n FROM stripe_events WHERE event_id=?',['evt_checkout_1']);assert.equal(events.n,1);
});
test('Assignment-graded and community reply/upvote emails honor notification preferences',async t=>{
  const sent=[];const f=await fixture(t,{mail:{send:async message=>{sent.push(message)}}});
  const a=await f.admin.request('instructor/assignments','POST',{courseId:'c1',title:'Practice',instructions:'Show your work'});
  await f.learner.request('courses/c1/enrollment','POST',{});
  await f.learner.request('assignments/'+a.body.id+'/submission','PUT',{body:'my work'});
  const submission=(await f.admin.request('instructor/overview')).body.submissions[0];
  sent.length=0;
  await f.admin.request('instructor/submissions/'+submission.id,'PATCH',{score:90,feedback:'Great work'});
  assert.equal(sent.length,1);assert.match(sent[0].subject,/graded/);assert.equal(sent[0].to,'learner@example.com');assert.match(sent[0].text,/90\/100/);assert.match(sent[0].text,/Great work/);

  // Turning the preference off means grading a second assignment sends nothing.
  await f.learner.request('settings','PATCH',{notifications:{assignmentGraded:false}});
  const a2=await f.admin.request('instructor/assignments','POST',{courseId:'c1',title:'Practice 2',instructions:'Show more work'});
  await f.learner.request('assignments/'+a2.body.id+'/submission','PUT',{body:'more work'});
  const submission2=(await f.admin.request('instructor/overview')).body.submissions.find(s=>s.id!==submission.id);
  sent.length=0;
  await f.admin.request('instructor/submissions/'+submission2.id,'PATCH',{score:80,feedback:'Good'});
  assert.equal(sent.length,0,'the learner opted out of assignment-graded emails');

  await f.learner.request('threads','POST',{channel:'#ui-ux-design',title:'Question',content:'How does this work?'});
  const threadId=(await f.learner.request('workspace')).body.communityThreads[0].id;
  sent.length=0;
  await f.other.request('threads/'+threadId+'/replies','POST',{content:'Try this.'});
  assert.equal(sent.length,1);assert.match(sent[0].subject,/replied/);assert.equal(sent[0].to,'learner@example.com');
  sent.length=0;
  await f.learner.request('threads/'+threadId+'/replies','POST',{content:'Thanks, replying to myself.'});
  assert.equal(sent.length,0,'authors are never emailed about their own replies');
  sent.length=0;
  await f.other.request('threads/'+threadId+'/vote','PUT',{});
  assert.equal(sent.length,1);assert.match(sent[0].subject,/upvoted/);
  sent.length=0;
  await f.other.request('threads/'+threadId+'/vote','PUT',{});
  assert.equal(sent.length,0,'a repeat vote from the same person sends nothing again');
});
test('Notification sweep is disabled until LMS_NOTIFICATIONS_TOKEN is configured',async t=>{
  const f=await fixture(t);
  assert.equal((await f.service.handle(new Request('http://localhost/api/notifications/sweep',{method:'POST'}))).status,503);
});
test('Notification sweep sends live-class reminders once and the opt-in weekly digest roughly weekly, and requires its bearer token',async t=>{
  const sent=[];const f=await fixture(t,{mail:{send:async message=>{sent.push(message)}},notificationsToken:'sweep-secret'});
  await f.learner.request('courses/c1/enrollment','POST',{});
  const soon=new Date(Date.now()+30*60000).toISOString(),later=new Date(Date.now()+86400000).toISOString();
  assert.equal((await f.admin.request('instructor/live-classes','POST',{courseId:'c1',title:'Live Q&A',startsAt:soon,meetingUrl:'https://meet.example.com/near'})).status,201);
  assert.equal((await f.admin.request('instructor/live-classes','POST',{courseId:'c1',title:'Tomorrow session',startsAt:later,meetingUrl:'https://meet.example.com/later'})).status,201);

  const sweep=(authorization)=>f.service.handle(new Request('http://localhost/api/notifications/sweep',{method:'POST',headers:authorization?{authorization}:{}}));
  assert.equal((await sweep()).status,403,'a request with no bearer token is rejected');
  assert.equal((await sweep('Bearer wrong')).status,403);

  sent.length=0;
  let result=await (await sweep('Bearer sweep-secret')).json();
  assert.equal(result.remindersSent,1,'only the class starting in ~30 minutes is due');
  assert.equal(sent.length,1);assert.match(sent[0].subject,/Starting soon/);assert.equal(sent[0].to,'learner@example.com');assert.match(sent[0].text,/near/);

  sent.length=0;
  result=await (await sweep('Bearer sweep-secret')).json();
  assert.equal(result.remindersSent,0,'the same class is never reminded twice');
  assert.equal(sent.length,0);

  assert.equal((await (await sweep('Bearer sweep-secret')).json()).digestsSent,0,'nobody has opted into the weekly digest yet');
  await f.learner.request('settings','PATCH',{notifications:{emailDigest:true}});
  await f.learner.request('lessons/l1/progress','PUT',{completed:true});
  sent.length=0;
  result=await (await sweep('Bearer sweep-secret')).json();
  assert.equal(result.digestsSent,1);
  const digestEmail=sent.find(m=>/weekly learning digest/i.test(m.subject));
  assert.ok(digestEmail);assert.equal(digestEmail.to,'learner@example.com');assert.match(digestEmail.text,/1 lesson/);

  sent.length=0;
  await sweep('Bearer sweep-secret');
  assert.equal(sent.filter(m=>/weekly learning digest/i.test(m.subject)).length,0,'a digest is not re-sent within the same week');
});
test('Promoting a learner to instructor requires a separate approval before they can use instructor tools',async t=>{
  const f=await fixture(t);
  const applicantId=f.users.find(u=>u.email==='other@example.com').id;
  await f.admin.request('admin/users/'+applicantId,'PATCH',{role:'instructor'});
  await f.other.request('auth/login','POST',{email:'other@example.com',password:f.password});
  assert.equal((await f.other.request('auth/session')).body.user.instructorStatus,'pending');
  assert.equal((await f.other.request('instructor/overview')).status,403,'a pending instructor cannot use instructor tools yet');
  assert.equal((await f.teacher.request('admin/users/'+applicantId+'/instructor-approval','PATCH',{status:'approved'})).status,403,'an ordinary instructor cannot approve applicants');
  assert.equal((await f.admin.request('admin/users/'+applicantId+'/instructor-approval','PATCH',{status:'nonsense'})).status,400);
  assert.equal((await f.admin.request('admin/users/'+applicantId+'/instructor-approval','PATCH',{status:'approved'})).status,200);
  assert.equal((await f.other.request('instructor/overview')).status,401,'approval revokes the applicant\'s session, like every other access change');
  await f.other.request('auth/login','POST',{email:'other@example.com',password:f.password});
  assert.equal((await f.other.request('auth/session')).body.user.instructorStatus,'approved');
  assert.equal((await f.other.request('instructor/overview')).status,200);
  const audit=(await f.admin.request('admin/audit')).body;
  assert.ok(audit.some(event=>event.action==='instructor.approved'&&event.target_id===applicantId));
});
test('Instructor accounts created before the approval workflow are grandfathered in as approved',async t=>{
  const dir=mkdtempSync(join(tmpdir(),'lms-grandfather-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));
  const file=join(dir,'test.sqlite');
  let db=openDatabase(file);
  const service=createService(db,seed,{});
  const user=client(service);
  await user.request('auth/register','POST',{name:'Legacy Teacher',email:'legacy@example.com',password:'a long strong test password'});
  await db.run("UPDATE users SET role='instructor' WHERE email='legacy@example.com'");
  assert.equal(await db.get('SELECT 1 AS x FROM instructor_approvals ia JOIN users u ON u.id=ia.user_id WHERE u.email=?',['legacy@example.com']),undefined,'no approval row exists yet for this simulated legacy account');
  db.close();
  db=openDatabase(file);t.after(()=>db.close());
  const row=await db.get('SELECT status FROM instructor_approvals ia JOIN users u ON u.id=ia.user_id WHERE u.email=?',['legacy@example.com']);
  assert.equal(row.status,'approved','reopening the database re-runs migrations, which grandfather pre-existing instructors in without an approval row');
});
test('Administrators can manually enroll a learner and view their per-course progress detail',async t=>{
  const f=await fixture(t);
  const learnerId=f.users.find(u=>u.email==='learner@example.com').id;
  assert.equal((await f.teacher.request('admin/enrollments','POST',{userId:learnerId,courseId:'c1'})).status,403,'manual enrollment requires manage_students, which an ordinary instructor lacks');
  assert.equal((await f.admin.request('admin/enrollments','POST',{userId:learnerId,courseId:'c1'})).status,201);
  assert.ok((await f.learner.request('workspace')).body.enrolledCourses.includes('c1'),'the learner is enrolled without ever calling the enrollment endpoint themselves');
  await f.learner.request('lessons/l1/progress','PUT',{completed:true});
  const detail=await f.admin.request('admin/users/'+learnerId+'/progress');
  assert.equal(detail.status,200);
  assert.equal(detail.body.enrollments.length,1);
  assert.equal(detail.body.enrollments[0].courseId,'c1');
  assert.equal(detail.body.enrollments[0].completedLessons,1);
  assert.equal(detail.body.enrollments[0].totalLessons,2);
  assert.equal(detail.body.enrollments[0].progress,50);
  assert.equal((await f.learner.request('admin/users/'+learnerId+'/progress')).status,403,'a learner cannot view this admin detail');
  assert.equal((await f.admin.request('admin/enrollments','POST',{userId:learnerId,courseId:'missing'})).status,404);
});
