import {mkdtempSync,cpSync,writeFileSync,readFileSync,mkdirSync,readdirSync,statSync,symlinkSync,existsSync} from 'node:fs';
import {join,resolve,relative} from 'node:path';
import {tmpdir} from 'node:os';
import {execFileSync} from 'node:child_process';
import {stripTypeScriptTypes} from 'node:module';
const root=process.cwd();const stage=mkdtempSync(join(tmpdir(),'academy-export-'));
for(const name of ['app','components','context','lib','tsconfig.json','package.json','package-lock.json','next-env.d.ts','styles.css'])if(existsSync(name))cpSync(name,join(stage,name),{recursive:true,filter:path=>!path.startsWith(join(root,'app/api'))&&!path.startsWith(join(root,'app/course/[id]'))&&!/app\/api($|\/)|app\/course\/\[id\]($|\/)/.test(path)});
symlinkSync(join(root,'node_modules'),join(stage,'node_modules'),'dir');
writeFileSync(join(stage,'next.config.mjs'),'export default {output:"export",trailingSlash:true,images:{unoptimized:true}};\n');
execFileSync(process.execPath,[join(root,'node_modules/next/dist/bin/next'),'build','--webpack'],{cwd:stage,stdio:'inherit',env:{...process.env,NEXT_TELEMETRY_DISABLED:'1'}});
const assets={};function walk(dir){for(const name of readdirSync(dir)){const path=join(dir,name);if(statSync(path).isDirectory())walk(path);else{const key='/'+relative(join(stage,'out'),path);assets[key]={body:readFileSync(path).toString('base64'),type:path.endsWith('.html')?'text/html':path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':path.endsWith('.txt')?'text/plain':path.endsWith('.json')?'application/json':path.endsWith('.svg')?'image/svg+xml':'application/octet-stream'}}}}walk(join(stage,'out'));
mkdirSync('dist/server',{recursive:true});
for(const name of ['service.mjs','auth.mjs','d1.mjs'])cpSync(join('server',name),join('dist/server',name));
const seedSource=stripTypeScriptTypes(readFileSync('lib/data.ts','utf8'),{mode:'strip'});writeFileSync('dist/server/seed.mjs',seedSource);
const schema=readFileSync('db/migrations/0001_lms.sql','utf8').split(';').map(s=>s.trim()).filter(Boolean);
writeFileSync('dist/server/assets.mjs','export default '+JSON.stringify(assets)+';\n');
writeFileSync('dist/server/schema.mjs','export default '+JSON.stringify(schema)+';\n');
cpSync('server/worker.mjs','dist/server/index.js');
console.log('Built Next frontend + persistent D1 backend for Sites.');
